### ISSUE TITLE
Menu operators not in Object menu (Blender 4.2.1)

### ISSUE THREAD

**Issue by timovirtaneva** [smokejohn/bl_apply_mods_shapekey#11]
Operators not in object menu

Apply All Modifiers (Keep Shapekeys)
Apply Subdivision (Keep Shapekeys)
Apply Chosen Modifiers (Keep Shapekeys)

**To Reproduce**
Installtion/Reinstallation has no effect

No error/info messages in console

**Desktop (please complete the following information):**
 - Blender Version: 4.2.1
 - OS: OSX 14.6.1

**Comment by LCDraws** [comment]
Happens in 4.3 too
Modules Installed () from 'D:\\blender\\SKkeeper\\__init__.py' into 'C:\\Users\\Potato\\AppData\\Roaming\\Blender Foundation\\Blender\\4.3\\scripts\\addons'
