### ISSUE TITLE
Apply Decimate ends on last ShapeKey instead of Base

### ISSUE THREAD

**Issue by Hunanbean** [smokejohn/bl_apply_mods_shapekey#5]
Using a decimate modifier and applying it with SKkeeper leaves the resulting model as the last shapekey in the list, instead of as Basis shape.

Thank you very much for this. You are a sanity saver!

Blender 3.3.2
SKkeeper 1.6

**Comment by smokejohn** [comment]
due to decimate changing vert counts it should lead to a crash in the script as described in #10 . Will add a fix for this. Closing this as potential duplicate
