### ISSUE TITLE
Blender Crashes when using this

### ISSUE THREAD

**Issue by ZnelArts** [smokejohn/bl_apply_mods_shapekey#7]
Blender 3.4.1
64GB ram memory
Mesh has 23k verts and 300 shape keys

Once Blender crashes the addon wont display anymore in blender menu nor in the addon list, a manual deletion of the file is required before installing the addon again.

**Comment by smokejohn** [comment]
Cannot reproduce this. I think the Addon should stay installed if it was installed then blender closed and opened again, instead of installing and then the app crashing.
