### ISSUE TITLE
IndexError: bpy_prop_collection[index]: index 2 out of range, size 2

### ISSUE THREAD

**Issue by RazorWolvendom** [smokejohn/bl_apply_mods_shapekey#8]
this error occoured as i tried to apply a Decimate and Shrinkwrap modifier
<img width="807" alt="ScreenShot_20230402071005" src="https://user-images.githubusercontent.com/44827474/229332697-aff2b9be-ab27-453e-96a2-32b15c48158c.png">

**Comment by swapmasterx** [comment]
Similar error here but for the mirror modifier
![Screenshot from 2024-08-07 19-39-16](https://github.com/user-attachments/assets/2637be47-9816-42b1-9113-3d63554e9d0c)

**Comment by swapmasterx** [comment]
https://github.com/smokejohn/SKkeeper/issues/10 Applied what was in this post and it solved the issue
